### ISSUE TITLE
Issue #2 Feature request

### ISSUE THREAD

**Issue by wajeehsheikh** [Manan311/My_Note#3]
Hi Manan,
Let me help you turn your notepad from the typical website font looking UI to a Handdrawn UI using the [PaperCSS](https://www.getpapercss.com/) library.

**Comment by Manan311** [comment]
Neat that would be awesome!

**Comment by wajeehsheikh** [comment]
Hi Manan, 

The feature was added successfully to your UI.

Here is what your new IU looks like:

<img width="724" alt="Screen Shot 2019-09-21 at 4 55 22 PM" src="https://user-images.githubusercontent.com/37858452/65379087-badda500-dc90-11e9-94ef-478b6bbe9bd4.png">

Take care,
Wajeeh

**Comment by Manan311** [comment]
That looks amazing and a lot more chalkboard like so users want to use it so it's great!! Thanks!!!
